### ISSUE TITLE
Stop words for keywords

### ISSUE THREAD

**Issue by chezou** [takuti/prelims#8]
Currently, keywords may contain meaningless words like "is", "to", "of", etc.

Here is my keywords extracted by prelims for https://chezo.uno/blog/2017-08-03_why-oss-based-machine-learning-is-good-3ab45a1a5e52/

```
keywords: [learning, the, machine, of, paper, papers, arxiv, to, is, deep]
```

Maybe, leveraging existing stop words like spaCy would work.

https://github.com/explosion/spaCy/blob/master/spacy/lang/en/stop_words.py

**Comment by takuti** [comment]
Good catch. In the current version, [`sklearn.TfidfVectorizer`](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) is initialized with `max_df=0.95, tokenizer=self.tokenizer`; the default value of its `stop_words` kwarg is `None`, which introduces no stop word filtering logic.

This setting was completely based on my heuristics that rely on a [custom tokenizer](https://github.com/takuti/takuti.me/blob/master/scripts/py/recommend.py#L10-L38).

#9 makes the configuration more flexible. You should become able to use arbitrary stop word list (or, simply say `stop_words='english'`). Let me know if this meets your needs.

**Comment by chezou** [comment]
Sounds reasonable to me to expose TfidfVectorizer option since `stop_words` enables us to set arbitrary list of stopwords.
https://github.com/scikit-learn/scikit-learn/blob/7e1e6d09bcc2eaeba98f7e737aac2ac782f0e5f1/sklearn/feature_extraction/text.py#L184-L192

Or, if you are okay to depend on SpaCy, it's nice to have a wrapper of SpaCy's stop words since it supports many languages.
https://github.com/explosion/spaCy/tree/master/spacy/lang

Japanese stop words looks not so great, tough.

**Comment by takuti** [comment]
Let's leave `stop_words` as optional for now; `spacy` is a big library, and depending on it just for the stopwords sake is a bit overwhelming. I added an example section to the docstring to reflect your idea though: https://github.com/takuti/prelims/pull/9/commits/9dc030e6238ed2e8600599c1b6c354d0de0b5a9e

Also notice that the change of `stop_words` may require you to modify `tokenizer` as well. Otherwise, tokenizer's behavior doesn't match with what's given as a stopwords list.

> .../sklearn/feature_extraction/text.py:401: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ll', 've'] not in stop_words.

To accommodate all possible scenarios and give maximum flexibility of tweaking the details, I believe we don't necessarily have to depend tightly on spacy.

**Comment by chezou** [comment]
Sounds reasonable to me! Thanks for your consideration.
